<?php

return array(
	'%blog_title%'            => '%%sitename%%',
	'%blog_description%'      => '%%sitedesc%%',
	'%page_title%'            => '%%title%%',
	'%page_author_login%'     => '%%name%%',
	'%page_author_nicename%'  => '%%name%%',
	'%page_author_firstname%' => '%%name%%',
	'%page_author_lastname%'  => '%%name%%',
	'%current_date%'          => '%%currentdate%%',
	'%post_title%'            => '%%title%%',
	'%category_title%'        => '%%term_title%%',
	'%taxonomy_title%'        => '%%term_title%%',
	'%category_description%'  => '%%category_description%%',
	'%category%'              => '%%term_title%%',
	'%post_author_login%'     => '%%name%%',
	'%post_author_nicename%'  => '%%name%%',
	'%post_author_firstname%' => '%%name%%',
	'%post_author_lastname%'  => '%%name%%',
	'%archive_title%'         => '',
	'%date%'                  => '%%date%%',
	'%day%'                   => '',
	'%month%'                 => '',
	'%year%'                  => '',
	'%author%'                => '%%name%%',
	'%tag%'                   => '%%term_title%%',
	'%search%'                => '%%searchphrase%%',
	'%description%'           => '%%excerpt%%',
	'%wp_title%'              => '%%title%%',
	'%request_url%'           => '',
	'%request_words%'         => '',
	'%404_title%'             => '',
	'%page%'                  => '%%page%%',
);
